pub const STEAMAUDIO_VERSION: u32 = audionimbus_sys::STEAMAUDIO_VERSION;
pub const STEAMAUDIO_VERSION_MAJOR: u32 = audionimbus_sys::STEAMAUDIO_VERSION_MAJOR;
pub const STEAMAUDIO_VERSION_MINOR: u32 = audionimbus_sys::STEAMAUDIO_VERSION_MINOR;
pub const STEAMAUDIO_VERSION_PATCH: u32 = audionimbus_sys::STEAMAUDIO_VERSION_PATCH;
